# Generated by Django 4.2.2 on 2023-06-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rg', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('expedition_time', models.CharField(blank=True, max_length=10, null=True)),
                ('expedition_org', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('cel', models.CharField(blank=True, max_length=17, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=17, null=True)),
                ('cep', models.CharField(blank=True, max_length=17, null=True)),
                ('reference', models.CharField(blank=True, max_length=17, null=True)),
                ('street', models.CharField(blank=True, max_length=17, null=True)),
                ('street_number', models.CharField(blank=True, max_length=17, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=17, null=True)),
                ('dad_name', models.CharField(blank=True, max_length=17, null=True)),
                ('partiner_name', models.CharField(blank=True, max_length=17, null=True)),
                ('isPj', models.BooleanField(blank=True, null=True)),
                ('hasGovAccount', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
